### ISSUE TITLE
Influxclient broken due to changes in influxdb repo

### ISSUE THREAD

**Issue by ZeissS** [rcrowley/go-metrics#105]
https://github.com/influxdb/influxdb/pull/1349 changed the Influx client. The current code does no longer compile:

```
.gobuild/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:19: undefined: client.ClientConfig
.gobuild/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:38: undefined: client.Series
.gobuild/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:44: undefined: client.Series
.gobuild/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:52: undefined: client.Series
.gobuild/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:60: undefined: client.Series
.gobuild/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:70: undefined: client.Series
.gobuild/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:82: undefined: client.Series
.gobuild/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:93: undefined: client.Series
.gobuild/src/github.com/rcrowley/go-metrics/influxdb/influxdb.go:106: client.WriteSeries undefined (type *client.Client has no field or method WriteSeries)
```

**Comment by rzab** [comment]
This is due to substantial changes in influxdb (master) client, it's api and protocol (urls, params etc.) it speaks with a server. The changes are incompatible with any released influxdb server AFAIK.
I have a patch in my fork, this is the diff: https://github.com/rzab/go-metrics/compare/rcrowley:master...master I'm not sure if I should PR this: the new influxdb api is anything but stable.

**Comment by mihasya** [comment]
I'll reiterate a comment I made a while ago - I think all the output clients should have their own repos, and this repo should merely aim to be vigorous in maintaining a reference of existing extensions. This applies to my own librato client as well, I just have no had the cycles to rip it out. This seems like a good opportunity to rip out the influx one, especially if the influxdb API itself is still not stable.

**Comment by jhiemer** [comment]
@mihasya I must say, that I agree with you. While the send function in https://github.com/rcrowley/go-metrics/blob/master/influxdb/influxdb.go may still exist as a data wrapper, the client itself should not be part of this implementation.

**Comment by mihasya** [comment]
Closing this as per-sink clients in this repo are not a sustainable way to move forward. I encourage you to create a separate client repo which imports this one and adds a reporter that works with whichever version of the influx API you require. Sorry it took so long to actually process this.
