### ISSUE TITLE
Influx dependency broken

### ISSUE THREAD

**Issue by GeertJohan** [rcrowley/go-metrics#108]
Influxdb's client package broke their public API.
I'll try to create a snapshot from the last valid version and PR with a new import path for go-metrics.

**Comment by mindscratch** [comment]
@GeertJohan thanks for doing this, it'll be nice once it gets merged in.

**Comment by GeertJohan** [comment]
Thanks @mindscratch 
I hope @rcrowley finds time soon to merge it :smile:

**Comment by mihasya** [comment]
Reiterating my opinion here: https://github.com/rcrowley/go-metrics/issues/105

**Comment by Inflatablewoman** [comment]
It would be great if this could be merged soon.

**Comment by omeid** [comment]
+1 @mihasya

**Comment by mihasya** [comment]
Closing because [this](https://github.com/rcrowley/go-metrics/issues/105)
