### ISSUE TITLE
statsd integration

### ISSUE THREAD

**Issue by isaldana** [rcrowley/go-metrics#111]
In an environment where you have many hosts (or many docker instances), it makes sense to aggregate the already aggregated stats.  statsd can be used for that.  Is there a better alternative?  I'm happy to create a patch.

**Comment by slayer** [comment]
:+1:

**Comment by mihasya** [comment]
I'm not 100% sure what you're proposing - adding `statsd` as an output client? If that is the case, see my comment [here](https://github.com/rcrowley/go-metrics/issues/105#issuecomment-72514186) on why that PR won't be accepted to this particular repo, though I'll be happy to add a link to a new repo to the README. Thanks!
