### ISSUE TITLE
Are counter metrics sent to StatHat reset between batches?

### ISSUE THREAD

**Issue by bfitzsimmons** [rcrowley/go-metrics#116]
When looking at my StatHat counters it was becoming apparent that the numbers were inflated by many times the actual count.  The code appears to be sending the count to StatHat at the desired interval, but it doesn't appear to be sending a delta from the last count sent.  Perhaps I'm reading it wrong.

Am I correct in thinking that StatHat is *not* expecting the entire count to be sent with each batch; simply the counter increments that have occurred since the last batch?  It seems like sending the entire count each time, as opposed to the delta between the current count and the last count, could lead to the grossly inflated counts seen in the StatHat interface.

#### Batch 1
* Increments since last count: 1000
* Total increments: 1000
* Increments sent to StatHat: 1000
* StatHat total increments: 1000

#### Batch 2
* Increments since last count: 1500
* Total increments: 2500
* Increments sent to StatHat: 2500
* StatHat total increments: 3500

#### Batch 3
* Increments since last count: 1000
* Total increments: 3500
* Increments sent to StatHat: 3500
* StatHat total increments: 7000

#### Batch 1
* Increments since last count: 1000
* Total increments: 1000
* Increments sent to StatHat: 1000
* StatHat total increments: 1000

#### Batch 2
* Increments since last count: 1500
* Total increments: 2500
* Increments sent to StatHat: 1500
* StatHat total increments: 2500

#### Batch 3
* Increments since last count: 1000
* Total increments: 3500
* Increments sent to StatHat: 1000
* StatHat total increments: 3500

**Comment by mihasya** [comment]
I personally don't know much about stathat, but in the case of other reporters, you send the whole count. If you want to chart the metric you're actually describing, you chart the derivative of the counter.

**Comment by mihasya** [comment]
Closing as we're going to [split individual clients off](https://github.com/rcrowley/go-metrics/issues/105#issuecomment-72514186) from the main repo.
