### ISSUE TITLE
InfluxDB support out of date

### ISSUE THREAD

**Issue by icholy** [rcrowley/go-metrics#124]
Please keep this issue open until an updated influxdb exporter is available. This should prevent other people wasting their time updating the current one.

#123 #117

**Comment by mihasya** [comment]
:+1:

**Comment by vrischmann** [comment]
FWIW, since @crosbymichael 's lib is not ready yet I made [this](https://github.com/vrischmann/go-metrics-influxdb) for now since I needed it for work.

Might be useful to someone else.

**Comment by crosbymichael** [comment]
@vincentbernat LGTM, you should just have a link to your pkg in the main docs.  Thanks!

**Comment by vrischmann** [comment]
Wrong mention :) Do you mean a link in the go-metrics README ? If that, I'll make a PR

**Comment by crosbymichael** [comment]
oops, ya.  I think linking to yours would be great.
