### ISSUE TITLE
Prefix support for CaptureDebugGCStats and RuntimeMemStats

### ISSUE THREAD

**Issue by vrischmann** [rcrowley/go-metrics#128]
Hi,

in http://godoc.org/github.com/rcrowley/go-metrics#CaptureDebugGCStats there's no way to control the name of the metrics registered.

I have multiple apps that have to report GC statistics to a InfluxDB server, and if I use this function as is, all the metrics will get merged by InfluxDB, and that's no good.

If you have the same problem, how do you handle it ?

As the title says, my suggestion is to add another function like CaptureDebugGCStatsWithPrefix or something that takes a prefix and passes it all the way down to the register call.

What do you all think ? I can work on a PR maybe today or tomorrow.

**Comment by mihasya** [comment]
@vrischmann could you create an implementation of `Registry` that wrapped a regular registry, but added a prefix to metric names, then pass that into `CaptureDebugGCStats`?

I would actually be interested in an implementation of that in `go-metrics`, should be a very small wrapper type on `StandardRegistry`. I have a use case for something similar as well.

**Comment by vrischmann** [comment]
Yep that would work. I'll work on that tonight or tomorrow night.
