### ISSUE TITLE
Feature Request: configure duration unit for printed timings

### ISSUE THREAD

**Issue by dt** [rcrowley/go-metrics#133]
When timing longer durations, sometimes the nanosecond-level output can be a little harder to read (lots of counting decimal places).

`Log` could accept a `scale` argument to apply to timers when they are printed, allowing callers to customize output to their liking.

**Comment by dt** [comment]
If this seems useful, happy to pull-req this:
https://github.com/dt/go-metrics/commit/bde2592dd106d8cf681810c90c76f2da8cbe0be5

**Comment by mihasya** [comment]
@dt just confirming my reading that this is backwards compatible and exposes a new method for folks that want to take advantage, correct? I think it's definitely worth a PR.

**Comment by dt** [comment]
Yep, included a wrapper method with the default scale to preserve backwards-compat.

**Comment by lmineiro** [comment]
:+1: on this one

**Comment by dt** [comment]
fixed in #134
