### ISSUE TITLE
Use interface for logger instead of log.Logger struct

### ISSUE THREAD

**Issue by hasnickl** [rcrowley/go-metrics#155]
It is useful to enable periodic metrics logging using ```metrics.Log()``` function, however it is hard coded to use the golang logger:
```
func Log(r Registry, freq time.Duration, l *log.Logger) {
	LogScaled(r, freq, time.Nanosecond, l)
}
```

This function should use an interface to support metrics logging with any library:

```
type Logger interface {
	Printf(format string, v ...interface{})
}

func Log(r Registry, freq time.Duration, l Logger) {
	LogScaled(r, freq, time.Nanosecond, l)
}
```

This allows metrics logging to utilize any logging library that provides ```Printf()```

**Comment by Galexrt** [comment]
+1

**Comment by mihasya** [comment]
TY for the fix
