### ISSUE TITLE
patch go-metrics/exp/exp.go to provide data in "/debug/vars"

### ISSUE THREAD

**Issue by saj1th** [rcrowley/go-metrics#160]
Would it make sense to patch go-metrics/exp/exp.go with something similar to https://github.com/codahale/metrics/blob/master/metrics.go#L311-L329 so that data would be available in   the endpoint "/debug/vars" ?

**Comment by saj1th** [comment]
+cc @Dieterbe

**Comment by mihasya** [comment]
See https://github.com/rcrowley/go-metrics/blob/master/exp/exp.go.
