### ISSUE TITLE
Ganglia exporter

### ISSUE THREAD

**Issue by codefx9** [rcrowley/go-metrics#164]
Is there a ganglia exporter for go-metrics? Thanks.

**Comment by mihasya** [comment]
There is [not one currently](https://github.com/rcrowley/go-metrics#publishing-metrics) BUT it is fairly easy to [contribute one](https://github.com/rcrowley/go-metrics/issues/121). I encourage you to do so!

**Comment by codefx9** [comment]
I found one here: https://github.com/appscode/metlia
