### ISSUE TITLE
Allow users to register the `expvar` endpoint with other HTTP routers

### ISSUE THREAD

**Issue by jprobinson** [rcrowley/go-metrics#166]
If a user is not using `http.ServeDefaultMux` with their server, the current `expvar` handler will not get exposed.

github.com/NYTimes/gizmo currently uses go-metrics under the hood and I would like to add a new 'EnableExpvar` configuration to the toolkit that would allow users to expose their metrics via HTTP.

To handle this, we'll need to expose the `http.Handler` used in the `exp` package so folks can register it with whatever router they need.

**Comment by genexp** [comment]
Yeah, we have the same problem.  :)

**Comment by mihasya** [comment]
ty @jprobinson for the fix
