### ISSUE TITLE
Sample interface is not sufficiently exported for use with StandardHistogram

### ISSUE THREAD

**Issue by kevingessner** [rcrowley/go-metrics#188]
I'd like to implement a new type of Sample, to be used as the sample underlying a Histogram.  Rather than forking, I'd prefer to implement it with a struct in my own package.  While the Sample interface is fully exported, there is one missing piece that prevents Samples from other packages from being used with the existing StandardHistogram (as returned by NewHistogram).

Any Sample can be used to construct the StandardHistogram, but StandardHistogram.Snapshot [explicitly asserts](https://github.com/rcrowley/go-metrics/blob/ab2277b1c5d15c3cba104e9cbddbdfc622df5ad8/histogram.go#L189) that the sample's Snapshot method returns a SampleSnaphot (rather than a Sample [as the Sample interface declares](https://github.com/rcrowley/go-metrics/blob/ab2277b1c5d15c3cba104e9cbddbdfc622df5ad8/sample.go#L24)).

Implementations of Sample in other packages cannot construct SampleSnapshots; while the type is exported, its fields are not, and there is no constructor for it.  This means that Sample implementations are hamstrung, and can't be used with Histograms.

I see several ways of fixing this:
1. Export the fields of SampleSnapshot.
2. Export a `NewSampleSnapshot(count int64, values []int64)` method for constructing SampleSnapshots
3. Change StandardHistogram to not require a SampleSnaphot but any Sample for its snapshot (by changing HistogramSnapshot).

Any of those would be acceptable, but I think 3 is the most general: there doesn't seem to be a strong reason to enforce that HistogramSnapshot has a SampleSnaphot rather than any Sample.

**Comment by mihasya** [comment]
OK, following this through a little bit.. All the protections are in place to ensure the read-only nature of the snapshot returned, which is cool and good. However, your point is very well taken that with the private fields and no constructor, we're defeating the whole point of using interfaces in some of these places. I have asked @rcrowley to rise from his lengthy slumber and weigh in on this just to make sure my understanding above is correct. Assuming it is, I am leaning towards option #2 - exposing a way to create `SampleSnapshots` while still guaranteeing their contract of being a read-only implementation of Sample.

Thank you for writing up the issue so concisely!

**Comment by mihasya** [comment]
(and now I'm actually going to do this!)
