### ISSUE TITLE
Documentation for InfluxDB Client Out of Date

### ISSUE THREAD

**Issue by catherinetcai** [rcrowley/go-metrics#199]
Current:

```
import "github.com/vrischmann/go-metrics-influxdb"

go influxdb.Influxdb(metrics.DefaultRegistry, 10e9, &influxdb.Config{
    Host:     "127.0.0.1:8086",
    Database: "metrics",
    Username: "test",
    Password: "test",
})
```

However, the influxdb.Config struct no longer exists. Directions should be updated to as follows:

```
import "github.com/vrischmann/go-metrics-influxdb"

go influxdb.InfluxDB(metrics.DefaultRegistry, 10e9, "127.0.0.1:8086", "database-name", "username", "password")
```

**Comment by mihasya** [comment]
Do you think you might be able to make a PR with the appropriate changes to the README? Given that the clients live outside the repo now, I'm inclined to just take that example out over fixing it myself. Thanks in advance!
