### ISSUE TITLE
Meter Memory Leak 

### ISSUE THREAD

**Issue by ariens-shopify** [rcrowley/go-metrics#201]
I `metrics.GetOrRegisterMeter()` many different meters to count events over the course of a second.  Every second I emit the meter values to my downstream monitoring system before calling `UnregisterAll()`. 

The resources of the meters are never GC'd and the memory climbs drastically when many (50-hundreds) meters are created.

**Comment by i19** [comment]
https://github.com/rcrowley/go-metrics/blob/master/meter.go#L37

**Comment by imkira** [comment]
This is supposed to solve it #197
