### ISSUE TITLE
OpenTelemetry exporter

### ISSUE THREAD

**Issue by vcastellm** [rcrowley/go-metrics#290]
Is anyone working on an OpenTelemetry exporter for this or is there any existing one?

I'm interested in such exporter and I can work on it.

**Comment by murphyzlaw** [comment]
@vcastellm did you do any work on this? I have the same requirement.

**Comment by vcastellm** [comment]
Nope and I won't have time to work on this because I'm not using it anymore, check opentelemetry-sdk
