### ISSUE TITLE
Implementing gauge as a callback

### ISSUE THREAD

**Issue by usmanismail** [rcrowley/go-metrics#35]
In the spirit of how gauge is implemented in the original codahale metrics shouldn't the gauge type "pull values"? Maybe by accepting a function pointer and starting a goroutine to call the function on a fixed interval to retrieve value. It can also use a task manager to avoid spawning too many goroutines.

**Comment by jhiemer** [comment]
@rcrowley I am quite new to Go. If I put all my Gauges into a map. How would I manage to retrieve news values for the map periodically?

**Comment by mihasya** [comment]
@jhiemer were you able to resolve your question? If you have all your Gauges in a map, you can do something like this (may not actually compile, but should get you most of the way):

```go
timer := time.NewTicker(5 * time.Second)
for {
    <- timer
    for label, gauge := range mapOfGauges {
        // do something with gauge
    }
}
```

Closing this issue, as it no longer appears to be an issue.

**Comment by mihasya** [comment]
@jhiemer You can also look at the implementation of various reporters, see [log.go](https://github.com/rcrowley/go-metrics/blob/master/log.go) for example.
