### ISSUE TITLE
Issue with MarshalJSON?

### ISSUE THREAD

**Issue by didip** [rcrowley/go-metrics#52]
Error message:
`registry.MarshalJSON undefined (type metrics.Registry has no field or method MarshalJSON)`

Code:

``` go
package main

import (
    "os"
    "time"
    "net/http"
    "github.com/rcrowley/go-metrics"
)

func main() {
    registry := metrics.NewRegistry()

    metrics.RegisterRuntimeMemStats(registry)

    go metrics.CaptureRuntimeMemStats(registry, time.Duration(2) * time.Second)

    http.HandleFunc("/", func(res http.ResponseWriter, req *http.Request) {
        data, _ := registry.MarshalJSON()    // This is where it breaks
        res.Write(data)
    })

    http.ListenAndServe("localhost:9999", nil)
}
```

**Comment by drichelson** [comment]
I came across this same question when using [PrefixedRegistry](https://github.com/rcrowley/go-metrics/blob/7839c01b09d2b1d7068034e5fe6e423f6ac5be22/registry.go#L148).

@rcrowley's suggestion doesn't work in my case: https://gist.github.com/drichelson/15de70b9576b1f3a640e

Am I doing something wrong? 
The behavior is the same with: `json.NewEncoder(writer).Encode(prefixedRegistry)`

**Comment by drichelson** [comment]
@rcrowley or anyone else- am I doing something wrong, or should this issue be revisited? Thanks
