### ISSUE TITLE
Choosing reservoir size and alpha of exponential decay sample

### ISSUE THREAD

**Issue by arnaudbriche** [rcrowley/go-metrics#54]
Hi,

Is there a formula to choose appropriate reservoir size and apha values of exponential decay sample so that they best represent the data that goes throught them for a specified amount a time (eg: default Timer use 1028, 0.015 which is supposed to represent roughly the last five minutes of data) ?

**Comment by yvasiyarov** [comment]
@arnaudbriche was you able to find any appropriate alpha values except 0.015 ?

**Comment by yvasiyarov** [comment]
I've find something, which can be useful for other guys:
https://github.com/VividCortex/ewma

> Consider a fixed-size sliding-window moving average (not an exponentially weighted moving average) > that averages over the previous N samples. What is the average age of each sample? It is N/2.

> Now suppose that you wish to construct a EWMA whose samples have the same average age. The  formula to compute the alpha required for this is: alpha = 2/(N+1). Proof is in the book "Production and  Operations Analysis" by Steven Nahmias.

> So, for example, if you have a time-series with samples once per second, and you want to get the  moving average over the previous minute, you should use an alpha of .032786885. This, by the way, is the constant alpha used for this repository's SimpleEWMA
